### ISSUE TITLE
[Feat] Including Prefix as a fallback

### ISSUE THREAD

**Issue by lezetho** [UnifierHQ/unifier#187]
### Checklist

- [X] The same feedback was not posted yet.
- [X] This is not a suggestion for the moderation team.
- [X] All info applicable to the issue has been attached.

### Problem

On a server that's used a lot (my server, for example) I have Revolt connected to Discord. However we usually send over 1,000 messages a day which rate limits the Discord bot and thus I get this error:

```2024-11-20 01:37:35 | ❌ ERROR    unifier.core           An error occurred!
Traceback (most recent call last):
  File "/home/container/unifier.py", line 597, in on_ready
    await bot.sync_all_application_commands()
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/client.py", line 2433, in sync_all_application_commands
    await self._connection.sync_all_application_commands(
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/state.py", line 783, in sync_all_application_commands
    await self.sync_application_commands(
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/state.py", line 845, in sync_application_commands
    await self.register_new_application_commands(data=data, guild_id=guild_id)
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/state.py", line 1059, in register_new_application_commands
    await self.register_application_command(app_cmd, guild_id)
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/state.py", line 1094, in register_application_command
    raise e
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/state.py", line 1090, in register_application_command
    raw_response = await self.http.upsert_global_command(self.application_id, payload)
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/http.py", line 972, in request
    raise HTTPException(response, ret)
nextcord.errors.HTTPException: 429 Too Many Requests (error code: 30034): Max number of daily application command creates has been reached (200)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/client.py", line 522, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/unifier.py", line 602, in on_ready
    await bot.register_new_application_commands()
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/client.py", line 2555, in register_new_application_commands
    await self._connection.register_new_application_commands(data=data, guild_id=guild_id)
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/state.py", line 1059, in register_new_application_commands
    await self.register_application_command(app_cmd, guild_id)
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/state.py", line 1094, in register_application_command
    raise e
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/state.py", line 1090, in register_application_command
    raw_response = await self.http.upsert_global_command(self.application_id, payload)
  File "/home/container/.local/lib/python3.9/site-packages/nextcord/http.py", line 972, in request
    raise HTTPException(response, ret)
nextcord.errors.HTTPException: 429 Too Many Requests (error code: 30034): Max number of daily application command creates has been reached (200)
```

### Proposed solution

If it gets a rate limit it'll switch to prefix mode and check hourly to see if the slash commands are working again. If they are then it'll disable prefix mode and if it still is then it won't change anything until.

**Comment by greeeen-dev** [comment]
Unless you're rebooting the bot frequently this is a rare ratelimit. Bridging has nothing to do with this ratelimit, that has its separate ratelimits (probably 150 messages per minute since that's Discord's webhook RL).

Also, Nextcord doesn't have hybrid commands, so we can't really implement this.
